### ISSUE TITLE
New GPL Audio Pack - Note on 5th Tones

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#156]
Max, as you will have seen I have prepared and uploaded a GPL licensed audio pack, thus eliminating the need to download audio so the toolkit will work out of the box. Of course the code that handles the extra audio sound set can be left in place so people can easily get a second sound set if they are fussed.

I do note that this audio set actually has a complete set of 5th tones (yay!). In fact it originally had audio 1 to 6 with 6 being a short first tone; I decided this was not sufficiently useful to leave in. There are other curiosities in the audio files if you take a look at the original version.

Anyway, I wanted to check with you: it seems like Pinyin Toolkit is not using the 5th tones any more. I thought we had opted for a fall-back system so that where an expression with 5th tones needs to be given audio the toolkit looks for an audio pack with 5th tones first but if none exists it falls back on the 4th tone. Have I misremembered this?

**Comment by batterseapower** [comment]
Great work on the GPL audio! That should make things much more convenient for our users.

The Toolkit still prefers to use fifth tone audio. I'm pretty sure this still works because it is tested, and I've double checked that the test passes.

However, I do note that the toolkit doesn't prefer audio packs that contain 5th tones to ones that do not, all other things being equal. So if you have 儿子 (er2 zi5) and packs like

Pack1: er2.mp3 zi4.mp3
Pack2: er2.mp3 zi5.mp3

It will simply choose to use one of the two randomly. Do you want this behaviour changed? I can make substituting a 4th tone sound for a 5th tone one as costly as if you were entirely missing a sound, or e.g. half as costly. (Where we choose the media pack with the lowest "cost").

**Comment by Nick3C** [comment]
Ah, I seeeee. That makes sense. I was confused by the fact that it didn't seem to be favouring the 5th tone packs and was trying to understand why.

I think your way is better. Otherwise we will favour the audio pack with 5th tones too much compared to any other packs and that pack will be used excessively. I think overall it is probably best left as is.

**Comment by batterseapower** [comment]
OK. If you change your mind let me know!
