### ISSUE TITLE
Hanzi Stats integration

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#157]
In a fit of Chinese New Year holiday coding fervour I rewrote a substantial chunk of Hanzi stats today (I was inspired by some of the changes made by JamesStrange in his traditional fork and wanted to merge them back into the simplified version in a way that benefits both traditional and simplified users).

Anyway, when I get a chance I will see whether I can manage a pytk branch to integrate the changes into the kit; hanzi stats is currently and unsupported and as the uploader I get queries in relation to it that I would prefer were dealt with under the auspice of the toolkit. Also I guess that it makes sense as PYTK users naturally use hanzi stats and this will reduce the support burden and let hanzi stats use some of the pytk featues such as guessing which field is used.

Max you will probably curse me for the messiness of the code (which was a mess to begin with and which I made worse ;) so I will keep the branch separate if I do get a chance to look at this. Might take a while though.

**Comment by batterseapower** [comment]
:) OK, looking forward to it.

新年快乐！

**Comment by Nick3C** [comment]
Uploaded an initial commit as I won't get time to work on it much today. It is in a usable but ugly form.

I have improved the plugin relative to the previous versions by merging the traditional and simplified forks. I have also added the in-Anki switch for traditional/simplified and seen/deck settings and made it support seperate fields for traditional and simplified lookup.

It manifestly needs a lot of work (not urgent) but I note some points for future references:

<ul>
<li>the missing / present stats don't work at the moment
<li>the code is extremely messy from the many minor modifications made to it; the method of generating python links is extremely ugly and inflexible.
<li>need to use PyTK's system of finding fields rather than specifying the field to use
<li>traditional stats are wrong, I presume because the fact is not new but the card is (and we only want to look at new cards)
<li>traditional stats do not include the characters which are the same in simplified; need to consider how to handle this (possibly use both fields so that traditional includes simplified)
<li>need to put the stats into statistics.py so all modules are using the same source of stats
<li>more stats would be nice i suppose, especially generating the seen and deck wide stats in one place, maybe also the breakdown of trad versus simp and have the switch just change the tables
</ul>

**Comment by batterseapower** [comment]
I've fixed it up somewhat (see the hanzistats branch of my repo on Github):
- Missing/present works
- Code much cleaner, and the Python link stuff is done in a nicer way
- Will try any of the names for the Expression field that the Tk knows about
- Reusing some constants from statistics.py (now statisticsdata.py)

I haven't looked at your points RE traditional stats or more stats. I also need to do some quick work to make it use the existing Hook mechanism rather than its own thing, which should let me pull most of the code out of the "anki" subdirectory.

(The "anki" subdirectory is my sin-bin for code I can't test because it is entwined too deeply into Anki itself)

**Comment by batterseapower** [comment]
There was an off-by-one error in the stats code, so that it thought that cards that were seen once were actually new. Maybe that explains the apparent error you saw with traditional cards? (I know you just started learning traditional, so maybe there are a lot of cards with only 1 repetition?)

**Comment by batterseapower** [comment]
I'm not sure what you mean by this:
- traditional stats do not include the characters which are the same in simplified; need to consider how to handle this (possibly use both fields so that traditional includes simplified)

I don't learn any traditional at all, but according to the stats I've learnt about 500 of the TW Ministry of Education list characters. This sounds about right to me. Presumably it shouldn't say you have learnt a traditional character just because you've learnt the simplified variant of the same character!

Am I misunderstanding, or is there no bug here?

**Comment by batterseapower** [comment]
I've added the TOP statistics to the main statistics pane for "Traditional", and I think thats its sufficiently done that I'm closing this ticket for now. If you find any bugs or have concrete suggestions feel free to start separate new tickets :-)
