### ISSUE TITLE
Hanzi Stats Simp / Trad Problems

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#160]
This ticket is further to our discussion in the other thread.

Ok, there are several issues here:
1. how should traditional / simplified be handled (i.e. should simplified characters be included in traditional statistics where they are the same)
2. at the moment neither approach is consistently adopted which causes anomalies in the stats
3. there are related problems with 'new' cards

In relation to point 1, I understand why you say simplified shouldn't be included in the traditional stat but I don't really agree. Traditional is a character set in and of itself which just happens to have some characters that are the same in traditional. For example 董. This character needs to be counted in both sets; if it is counted only in simplified then you are fiddling the traditional stats because you have seen this character and it is incorrect to say that you have not. Not counting them presumes that traditional characters are 'extra' ones known beyond simplified characters. This is a possible approach but it would require ome changes to the way the stats are described and handled. I also do not think it is a good approach; it would require us to allow for traditional-focuses students who are studying 'extra' simplified characters.On balance it is much simpler to just treat the two as separate and discrete sets (and it is more technically correct to do so; if you know simplified characters that are the same as traditional characters it is true to say you know that many traditional characters; i.e. traditional means 'unsimplified').

This leads on to the current problem, number 2. Whichever way we handle issue 1 at the moment we use a part-way solution that is not in accord with either approach. If we have characters that are the same in both simplified and traditional sets (or multi-character words with characters that are the same in both simp and trad) then the traditional field is not filled with data. As the new stats feature only looks in the traditional field these characters are omitted. However, if we have a word that contains one traditional character and one character that is the same in both traditional and simplified then the traditional field will be filled with both. This is the desired behaviour (as we don't want that field filling if it doesn't need to be - card generation issues, and messiness issues) but not for counting in this way. But it has the consequences that only SOME of the characters that are the same in both traditional and simplified are included in the stats.

I am not quite sure how to handle this issue... I might be tempted to have traditional look in both expression and traditional fields but this is sort of a fiddle and will create anomalies in the stats (traditional stats will include simplified characters when this should not be the case). It also generates further problems in relation to issue 3.

To explain issue 3, there is currently a problem in that 'seen' cards we should only count a character as seen where it has been reviewed directly (i.e. if you have reviewed the simplified card in a fact this does not mean you have reviewed and seen the traditional card in that fact and vice versa). The only obvious way to deal with this is to look for a model string containing Trad or Traditional and then not count those cards as seen for simplified but count them as the only criteria for 'seen' in traditional. This is important in my deck for instance; I have reviewed probably something like 300 traditional characters, however because I have reviewed facts with traditional characters in them the reported number is over 2000. This is simply incorrect and makes the 'seen' figure nearly useless for the non-primary character set.

**Comment by batterseapower** [comment]
1. I think you've misunderstood me: I'm totally happy with characters that are the _same_ in traditional and simplified being reported as "learnt" when you choose either a Traditional or Simplified view. Saying that traditional characters are "extras" doesn't really work for people who are learning Chinese for Taiwan/Hong Kong anyway.
2. I see what you are getting at now! Actually, the current stats code just looks at the _expression_ field, so what you describe isn't exactly what happens. However you are certainly right to say that it should consider the Traditional and Simplified fields as well. Some possibilities:
   - Assume the Expression is simplified or traditional based on the preferred character set setting
   - Or, consider _all three_ fields in the statistics but do not report the "3500+" statistic in the stats view. This is the only one that will report bad data if we do this, because we have the frequency data  / specific stats data in the appropriate character sets anyway. But the 3500+ stat will show even very simple Simplified characters as being rare traditional ones, which is a bit odd :-)
   - Or, implement an algorithm for converting traditional to simplified and vice versa, and for testing traditional/simplified status of a character. We can then use this to filter out characters from all three fields that are not in the correct set.
     - We could actually use Google translate for this by sending it the entire set of candidate characters and asking it to convert either way, then comparing the results. 
     - Won't work if you are offline :-( unless we implement our own conversion routine
     - The Google traditional/simplified translator won't be able to use context to disambiguate the unsimplification process because we should send it a character _set_ rather than a simple concatenation of all expressions in the deck, to keep size down. This is likely a minor issue though.
3. Right, I was wondering about this. So we could:
   - (Your suggestion) Try and work out if a card is showing the traditional/simplified field by looking at the card name. Then include the contents of the "appropriate" field in the set of seen character, for some definition of "appropriate".
   - Alternatively we could parse the card question template to see which fields are being shown, then scan _all_ those fields for Hanzi, which are considered to be seen if the card is. This requires less setup on the part of the user and is my preferred option.

Thoughts?

**Comment by batterseapower** [comment]
Right.

In head:
- I have added code that does a rough test for if a character is traditional or simplified, using cjklib and the Unihan database. This is used for stats filtering, and appears to work pretty well on my deck. (i.e. it doesn't report a lot of simplified characters in the stats about my progress on traditional)
- It is much more cunning about working out cards correspond to learning which things. It parses the question text for seen cards to work out what it is testing, and then only counts characters in those tested fields as seen, rather than everything on the fact.

Since that should resolve both your problems I'm closing the ticket.

**Comment by Nick3C** [comment]
sorry for the slow reply. Was very hectic last week.

This sounds like an excellent approach. Good job.
