### ISSUE TITLE
'Smart' Autoblanking Feature

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#6]
Selective blanking feature. Save the PREVIOUS values of each field
somewhere when filling the fields [possibly in hidden html in each
filled field]. When doing a lookup check see if there is a change from
the previous lookup value and the current value (i.e. if they have not
been edited). If not edited then blank and replace, if edited then
leve alone.

**Comment by Nick3C** [comment]
The changes you made a couple of days ago make this work properly for me (at least from the last 20 minutes of playing with it). However, the visual artefacts and font problems from putting the link at the start of the field still persist.

Can the pinyin toolkit link be be moved to the end of the field as this solves the visual problem? Otherwise would you like me to send you a sample deck demonstrating the problem?

**Comment by Nick3C** [comment]
Also, any thoughts on transitional arrangements for older cards?

At the moment auto-blanking is basically broken for older cards as if you remove the expression the fields won't be blanked even for auto-generated cards because the tag is missing. This means they must be manually blanked (each field) which sort of defeats the purpose of auto-blanking :)

It may be best to run a conversion routine to add the tag to all old cards i.e. default to assuming auto-generation rather than assuming manual creation. The inconvenience of no auto blanking for those cards is more bothersome than the risk of overwriting a field on the few occasions where this may be a problem.

**Comment by batterseapower** [comment]
Nick - I haven't forgotten about your visual problem! I'm going to investigate your proposed solution for that before I release any new official version.

RE a conversion routine: that is certainly a possibilty. We could also apply the old auto-blanking rules to cards created before the date the PyTk 0.7 is installed.

Is auto-blanking actually useful for old cards though? I personally only use auto-blanking when entering new cards when I find that I've got the characters for some vocab item wrong, or I type in something which Anki detects as already being in the deck. So losing it for cards I've already added is no big deal.

**Comment by Nick3C** [comment]
1. Good good.
2. Applying the old rules to pre-0.7 cards would be fine as well (although I worry abut what happens if an old card is regenerated so as to have tags). Might it be simpler to apply the same rules but have a one-off conversion process?
3. I use auto-blanking quite often with older cards as well. I use it as a way to quickly empty the whole card so that the data can be regenerated.

Here's an example: this morning I had a card which I wanted to change from 烂头 to 烂头岛. This is effectively the same card so I wanted to simply update the word to be more consistent with other cards and in accordance with standard usage. However this requires the following fields to be changed: expression, pinyin, colour, traditional, and audio (5 fields). The easiest way to deal with this is to blank the whole card and allow the toolkit to regenerate these fields (which is does correctly) and this could previously be done in half a second by cutting, tab, tab-shift and pasting.

Without auto-blanking each field has to be blanked manually (eek). Of course, the new smart auto-blanking method is better because it removes the need to blank the card at all (the generated parts would simply appear once the expression field was editing) but this can't happen automatically for older cards.

**Comment by batterseapower** [comment]
Here is another alternative: provide a shortcut key/button for clearing all fields in the add fact dialog. This minimises the risk of accidental data loss with over-enthusiastic auto blanking.

Thoughts?

**Comment by Nick3C** [comment]
Sure, I see where you are coming from.

Given that we now have proper auto-blanking you are probably right and something like this is a better way to handle the transition in a forward-looking way..

I presume you mean in the edit field dialogue as well?

**Comment by batterseapower** [comment]
I thought I posted something about the visual problem, but it's vanished.

Anyway, I've found out why the bug occurs. This script shows it:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from PyQt4 import QtGui, QtWebKit

app = QtGui.QApplication(sys.argv)

widget = QtGui.QWidget()
widget.resize(300, 300)
widget.setWindowTitle('Non-Bug Reproduction')

te1 = QtWebKit.QWebView(widget)
te1.setHtml(u'<a href="foo"><span style="font-size:50px"><a name="bar"></a>a</span></a>')

te2 = QtWebKit.QWebView(widget)
te2.setHtml(u'<a href="foo"><span style="font-size:50px">a</span></a>')

vbox = QtGui.QVBoxLayout()
vbox.addWidget(te1)
vbox.addWidget(te2)
widget.setLayout(vbox)

widget.show()

sys.exit(app.exec_())
```

Basically the "a" in both boxes should be the same size, but it isn't. This is because generating nested a tags is in violation of the HTML specification (section 12.2.2 in http://www.w3.org/TR/html401/struct/links.html#edef-A), and the Color field has a link wrapped around it in the sample deck.

Moving the a tag to the end "fixes" it because it causes the a tag to be closed when it just when was about to be closed anyway. Nasty though. 

I have a possible solution (inspired by the Anki sources). Put the pinyin-toolkit link at the end as you suggest, but insert a zero-width speace (u200b) rather than an actual space. Annoyingly you can still tell thats its there (using the arrow keys, you seem to have to press twice to move across a single character), but at least its not so wide...

**Comment by batterseapower** [comment]
Right. Your visual bug should be fixed now - I pushed a fix which uses u200d instead (the "Zero Width Joiner"), which doesn't produce any cursor weirdness or visual artifacts at all.

**Comment by batterseapower** [comment]
I've added a blanking shortcut, Ctrl+Alt+b. I think this ticket is done now!

**Comment by Nick3C** [comment]
excellent :)
