### ISSUE TITLE
Pinyin in reading field not colorizing itself

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#64]
Try this one...
下载

**Comment by batterseapower** [comment]
I think you mean the "meaning" field. Hmm yeah, ugly. Fixing this requires extra processing to detect pinyin that occurs without any corresponding characters in the meaning. 

We get away without this at the moment because I'm just parsing out CEDICT stuff that looks like 黄石市[Huang2 shi2 shi4], which is relatively easy to spot during measureword detection.

Probably not too hard to fix.

**Comment by Nick3C** [comment]
Ah, if that's what it is then the answer is to switch to regex for pinyin detection. Then it should pick it out of any arrangement, even if there is no space. I think I linked to someone else's regex in another thread (as that is on the to do list). 

That may even have future benefits, when we come to play with True pinyin.

**Comment by batterseapower** [comment]
Should be easy to fix now we have better pinyin parsing. Moving the priority up.

**Comment by Nick3C** [comment]
great. That is a core backend upgrade that has been needing some attention for a while.

**Comment by batterseapower** [comment]
Works beautifully now!
