### ISSUE TITLE
Hanzi Graph - Refresh Bug & Show/Hide Bug

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#65]
as per title.

**Comment by batterseapower** [comment]
Picky-picky :-)

This is suprisingly hard to achieve because Anki doesn't expose enough data as class members. See graphs.py in the method onRefresh(). We need to either:
- Add ourselves to the widgets array (impossible, because it's method-local)
- Add a new handler to the refresh button (seemingly impossible, because it's only accessible as a child on of an inaccessible hbox which is in turn simply the layout of a IntervalGraph which is the child of something.... and so on)

Tricky. The real solution would be if Damien provided a proper interface that plugins could provide a graph by using.

NB: seems like Show/Hide is broken too (quite badly! get an exception). Similar reason.

**Comment by Nick3C** [comment]
well, let's put this on hold until after 0.05 is released. Then we can ask Damien for some hooks there. He is very good about this sort of thing.

**Comment by batterseapower** [comment]
Changes to Anki appear to have made this possible (or else I missed something earlier). Should be fixed in my fork.

**Comment by Nick3C** [comment]
oh, great!
