### ISSUE TITLE
Special Lookups Numbers [done], Percentages, Years, Decimals

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#9]
In fact numbers (when in the color hanzi
field) should really never be colorised. If they are things get very
messy. When I decided to add dictionary entries for numbers above 10
(to allow for sexy conversion into full-form pinyin) character
colorisation got excited because the pinyin word order doesn't match
the character order. In addition there are other troubles such as 335
being looked up as 33, 5. I never could decide what to do about years
(eg 2000 could be either two thousand or 200年).

Any thoughts on this? We could always color number in colored
characters differently. I rather like the blue color used as number 6
in the shortcut key plugin. What do you think?

**Comment by Nick3C** [comment]
I have written a function to convert western numbers into Chinese ones. Took a while, but it is pretty neat (though sure you will want to tidy up the ends). The idea is that we can handle the numbers perfectly if they are in character form so... we convert them for the colored hanzi and before pinyin generation. All problems solved and we get the benefit of having chinese numbers in the colored hanzi too.

**Comment by Nick3C** [comment]
later we can add some neat tricks to deal with % conversion too, and even do a similar trick if there is a 年 after it (to treat with dates two zero zero zero, not 2000, etc

**Comment by Nick3C** [comment]
This is better. how about coloring numbers differently so that it is clear they are not 5th tones?

**Comment by Nick3C** [comment]
Max, I just noticed that this doesn't actually work as I had been intended it. I had intended it to replace the dictionary lookup for numbers (because it is impracticle to do this for every single number).  However, it seems only to deal with pinyin and character colorisation; the actual pinyin generated is not correct.

eg 1432 returns shí sì sān shí èr

my intention had been to replace 1432 with:
一千三十二 _before_ passing it to dictionary lookup. i.e. any numbers in the phrase are removed before the dictionary lookup.

Note that I have just pushed a version which includes the numbers I cropped from the system dictionary to work in the meantime.

**Comment by batterseapower** [comment]
I don't think that I ever actually wired in the code for generating better readings for numbers, all I did was fix up the code you wrote and added some tests for it.

This should be a high priority, so when I'm back home (I've been in France for a week) I'll look into doing this. % and nian support should be straightforward as well.

**Comment by Nick3C** [comment]
ah a see, that would explain it :)

For your ref:
[n]% converts to 百分之[n]

fractions are easier:
the full spop just converts to 点
but we will need to use a regex to only replace when there is a number of the left and right side of the period.

**Comment by batterseapower** [comment]
I've mostly implemented this in my branch. I support natural numbers, decimals and years. Fractions and percentages are easy - I'll probably do them soon.

**Comment by batterseapower** [comment]
Support fractions and percentages in reading + meaning generation. Closed by af5dfcfc3073ed2a0015d3cae07f19a0b75cfd21

**Comment by Nick3C** [comment]
We need to add support for commas in the text (for the thousand separator (although not really allowed in Chinese they are used by learners). Solution is just cut them if there is a number on left and 3 figures on right (eg 34,324 or 34,324,432).

I think we should add an underline on the number to indicate which pinyin these items represent. Because there is not direct corrospondence of pinyin to character something like this is needed or the a phrase like 我有4543个朋友们. it's alright in simple sentences but as they get more complicated it gets harded to see what it what.
