### ISSUE TITLE
Tun Transaltion On/ff (Add new language to the list: "Translation Disabled")

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#90]
user reports can't turn off without manual editing of config.db

This seems like a nice way to turn off translation without adding extra checkboxes.

**Comment by batterseapower** [comment]
I've pushed some changes to my tree which add small checkboxes by every field to allow disabling of modification of that field. A nice uniform solution.

I'm leaving this ticket open because when you turn off both MW and Meaning generation CPU usage seems to spike?? Can you replicate this? I have no idea why.

**Comment by Nick3C** [comment]
That's a nice idea.

I don't get any checkboxes I'm afraid (although generation still works).

Also preferences gives an error:
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 123, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 146, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 41, in **init**
    self.setUpViewPreview()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 62, in setUpViewPreview
    wantcheckbox = pinyin.config.updatecontrolflags[key] is not None
KeyError: 'links'

**Comment by batterseapower** [comment]
Ah.. interesting. Your problem is caused by some legacy crap in your configuration file. I need to make the config handling more robust, clearly.

**Comment by batterseapower** [comment]
I've gone to some trouble to make the toolkit clean up dirty old configuration data. Does it work now?

**Comment by Nick3C** [comment]
Yes that works now. sweet. That should also take care of other issues I had mentioned previously about config file not creating new values. nice one.

Note: the generation needs to be tweaked so that if trad = simp then nothing is returned. The reason for this is that a sensible setup will allow for auto-generation of cards in the traditional chinese model if the field is not empty. If the toolkit fills the field where they are the same then unwanted cards will be generated.

I modified the routine in my branch, but you haven't merged it yet.

**Comment by Nick3C** [comment]
although I presume you know that it doesn't create forceexpressiontobesimptrad, as yet (so this can't be used yet).

**Comment by batterseapower** [comment]
Well, it's true that there's no UI for forceexpressiontobesimptrad. You can actually try experimenting with it by doing:

1) Comment it out in defaultsettings
2) Start anki and then close it. My new code will wipe out the old setting for forceexpressiontobesimptrad because it now looks like junk.
3) Uncomment it in defaultsettings and change the default value to True
4) Start anki again

In fact, my unit tests say that forceexpressiontobesimptrad will do the right thing, so it will probably even work :)

I'll raise a new ticket for adding UI to forceexpressiontobesimptrad.

**Comment by Nick3C** [comment]
yep it works. needed a minor fix at updater.py line 249 but it's done now. (otherwise it wouldn't be over-written because the field was full)
