### ISSUE TITLE
Limit Log Size & Move to %temp%

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#98]
Need to add a limit before over-writing old logs.
Last one got to 16mb.

Probably also need to store the log in %temp%

**Comment by Nick3C** [comment]
hmmm, this second my log is 0.99gb... that is unacceptably big, really :)

**Comment by batterseapower** [comment]
I'm not very interested in doing anything about this for two reasons.

1) Users logs will be much smaller than ours because we have extra logging turned on
2) When Anki upgrades to Python 2.5 the code will automatically start using the rotating file handler which prevents the log growing beyond 40kb

That said, there is already code in place to delete the log whenever Anki is started. (logger.py). Would you like to take a look into why it doesn't work on Windows?

**Comment by Nick3C** [comment]
ok, that sounds fine then. At a guess, the faliure to delete might be linked to the fact that I use multiple copies of anki (different incriments of code, different decks, etc). Windows locks the log file when it is in use so that is presumably why mine is growing so much larger.

I take your point. Not serious enough to worry about (grrr, 1gb :) )

**Comment by batterseapower** [comment]
Yeah, if it's locked then it can't be deleted. If you quit all your Anki instances and then start a new one it should be deleted though?

**Comment by Nick3C** [comment]
yep, that seems to be what is happening. It generally works, but it gets huge if I have had these multiple copies open, etc (as I have today while coding, etc).

also, sometimes anki will not close properly and will sit silently in the background, holding open the log.

Not to worry, you're right that those 2 reasons are a sufficient fix.
